import { Router } from "express";
import { advancedModulesRouter } from "./advancedModules";
import { antiBanBotRouter, antiBanDashboardRouter } from "./antiBan";
import { authRouter } from "./auth";
import { automatedLogsRouter } from "./automatedLogs";
import { botDevApiRouter } from "./botDevApi";
import { clipsRouter } from "./clips";
import { coursesRouter } from "./courses";
import { dashboardRouter } from "./dashboard";
import { databaseMaintenanceRouter } from "./databaseMaintenance";
import { dafScaleRouter } from "./dafScale";
import { devRouter } from "./dev";
import { dmBarRouter } from "./dmBar";
import { emojiClonerRouter } from "./emojiCloner";
import { fivemRouter } from "./fivem";
import { fivemPd7Router } from "./fivemPd7";
import { fivemActionsRouter } from "./fivemActions";
import { fivemFinanceRouter } from "./fivemFinance";
import { globalBlacklistRouter } from "./globalBlacklist";
import { giveawaysRouter } from "./giveaways";
import { guildsRouter } from "./guilds";
import { healthRouter } from "./health";
import { imageAntiSpamRouter } from "./imageAntiSpam";
import { kickNotificationsRouter, kickWebhookRouter } from "./kickNotifications";
import { livesRouter } from "./lives";
import { logsRouter } from "./logs";
import { manualRegistrationRouter } from "./manualRegistration";
import { manualPaymentsRouter } from "./manualPayments";
import { fivemOrdersRouter } from "./fivemOrders";
import { missionToolsRouter } from "./missionTools";
import { nexTechSalesRouter } from "./nexTechSales";
import { openDutyNotificationsRouter } from "./openDutyNotifications";
import { mediaRouter } from "./media";
import { panelImagesRouter } from "./panelImages";
import { paymentAdminRouter, paymentsRouter, paymentWebhooksRouter } from "./payments";
import { botRegistrationRouter, checkoutRouter, customerPlansRouter, plansRouter, workspacePlansRouter } from "./plans";
import { policePatrolReportsRouter } from "./policePatrolReports";
import { policeHiddenChannelRouter } from "./policeHiddenChannel";
import { priceTablesRouter } from "./priceTables";
import { persistentImagesRouter } from "./persistentImages";
import { reportForwardingRouter } from "./reportForwarding";
import { rhAdminRouter } from "./rhAdmin";
import { selfBotProtectionRouter } from "./selfBotProtection";
import { serverBackupsRouter } from "./serverBackups";
import { settingsRouter } from "./settings";
import { botLivesRouter, socialNotificationsRouter } from "./socialNotifications";
import { socialsRouter } from "./socials";
import { ticketsRouter } from "./tickets";
import { transcriptsRouter } from "./transcripts";
import { temporaryVoiceRouter } from "./temporaryVoice";
import { usersRouter } from "./users";
import { voiceRecorderRouter } from "./voiceRecorder";
import { xMonitorRouter } from "./xMonitor";
import { xWebhookRouter } from "./xWebhook";

export const apiRouter = Router();

apiRouter.use("/health", healthRouter);
apiRouter.use("/advanced-modules", advancedModulesRouter);
apiRouter.use("/anti-ban", antiBanBotRouter);
apiRouter.use("/image-anti-spam", imageAntiSpamRouter);
apiRouter.use("/auth", authRouter);
apiRouter.use("/automated-logs", automatedLogsRouter);
apiRouter.use("/bot", botDevApiRouter);
apiRouter.use("/bots", botLivesRouter);
apiRouter.use("/bots", antiBanDashboardRouter);
apiRouter.use("/clips", clipsRouter);
apiRouter.use("/courses", coursesRouter);
apiRouter.use("/dashboard", dashboardRouter);
apiRouter.use("/database-maintenance", databaseMaintenanceRouter);
apiRouter.use("/daf-scale", dafScaleRouter);
apiRouter.use("/dev", devRouter);
apiRouter.use("/dm-bar", dmBarRouter);
apiRouter.use("/emoji-cloner", emojiClonerRouter);
apiRouter.use("/fivem", fivemRouter);
apiRouter.use("/fivem-pd7", fivemPd7Router);
apiRouter.use("/fivem-actions", fivemActionsRouter);
apiRouter.use("/fivem-finance", fivemFinanceRouter);
apiRouter.use("/global-blacklist", globalBlacklistRouter);
apiRouter.use("/giveaways", giveawaysRouter);
apiRouter.use("/kick", kickWebhookRouter);
apiRouter.use("/kick-integration", kickNotificationsRouter);
apiRouter.use("/users", usersRouter);
apiRouter.use("/guilds", guildsRouter);
apiRouter.use("/lives", livesRouter);
apiRouter.use("/mission-tools", missionToolsRouter);
apiRouter.use("/nex-tech-sales", nexTechSalesRouter);
apiRouter.use("/open-duty-notifications", openDutyNotificationsRouter);
apiRouter.use("/media", mediaRouter);
apiRouter.use("/panel-images", panelImagesRouter);
apiRouter.use("/payments", paymentsRouter);
apiRouter.use("/admin/payments", paymentAdminRouter);
apiRouter.use("/webhooks", paymentWebhooksRouter);
apiRouter.use("/plans", plansRouter);
apiRouter.use("/checkout", checkoutRouter);
apiRouter.use("/bot-registration", botRegistrationRouter);
apiRouter.use("/customer", customerPlansRouter);
apiRouter.use("/workspaces", workspacePlansRouter);
apiRouter.use("/police-patrol-reports", policePatrolReportsRouter);
apiRouter.use("/police-hidden-channel", policeHiddenChannelRouter);
apiRouter.use("/price-tables", priceTablesRouter);
apiRouter.use("/persistent-images", persistentImagesRouter);
apiRouter.use("/report-forwarding", reportForwardingRouter);
apiRouter.use("/rh-admin", rhAdminRouter);
apiRouter.use("/tickets", ticketsRouter);
apiRouter.use("/transcripts", transcriptsRouter);
apiRouter.use("/temporary-voice", temporaryVoiceRouter);
apiRouter.use("/voice-recorder", voiceRecorderRouter);
apiRouter.use("/logs", logsRouter);
apiRouter.use("/manual-registration", manualRegistrationRouter);
apiRouter.use("/manual-payments", manualPaymentsRouter);
apiRouter.use("/fivem-orders", fivemOrdersRouter);
apiRouter.use("/self-bot-protection", selfBotProtectionRouter);
apiRouter.use("/server-backups", serverBackupsRouter);
apiRouter.use("/settings", settingsRouter);
apiRouter.use("/social-notifications", socialNotificationsRouter);
apiRouter.use("/socials", socialsRouter);
apiRouter.use("/x-monitor", xMonitorRouter);
apiRouter.use("/x-webhook", xWebhookRouter);
