import { Router } from "express";
import { authRouter } from "./auth";
import { botDevApiRouter } from "./botDevApi";
import { clipsRouter } from "./clips";
import { dashboardRouter } from "./dashboard";
import { devRouter } from "./dev";
import { fivemRouter } from "./fivem";
import { giveawaysRouter } from "./giveaways";
import { guildsRouter } from "./guilds";
import { healthRouter } from "./health";
import { imageAntiSpamRouter } from "./imageAntiSpam";
import { kickNotificationsRouter, kickWebhookRouter } from "./kickNotifications";
import { livesRouter } from "./lives";
import { logsRouter } from "./logs";
import { settingsRouter } from "./settings";
import { botLivesRouter, socialNotificationsRouter } from "./socialNotifications";
import { socialsRouter } from "./socials";
import { ticketsRouter } from "./tickets";
import { usersRouter } from "./users";
import { xMonitorRouter } from "./xMonitor";
import { xWebhookRouter } from "./xWebhook";

export const apiRouter = Router();

apiRouter.use("/health", healthRouter);
apiRouter.use("/image-anti-spam", imageAntiSpamRouter);
apiRouter.use("/auth", authRouter);
apiRouter.use("/bot", botDevApiRouter);
apiRouter.use("/bots", botLivesRouter);
apiRouter.use("/clips", clipsRouter);
apiRouter.use("/dashboard", dashboardRouter);
apiRouter.use("/dev", devRouter);
apiRouter.use("/fivem", fivemRouter);
apiRouter.use("/giveaways", giveawaysRouter);
apiRouter.use("/kick", kickWebhookRouter);
apiRouter.use("/kick-integration", kickNotificationsRouter);
apiRouter.use("/users", usersRouter);
apiRouter.use("/guilds", guildsRouter);
apiRouter.use("/lives", livesRouter);
apiRouter.use("/tickets", ticketsRouter);
apiRouter.use("/logs", logsRouter);
apiRouter.use("/settings", settingsRouter);
apiRouter.use("/social-notifications", socialNotificationsRouter);
apiRouter.use("/socials", socialsRouter);
apiRouter.use("/x-monitor", xMonitorRouter);
apiRouter.use("/x-webhook", xWebhookRouter);
