import { ActionRowBuilder, ButtonBuilder, ButtonStyle, MessageFlags, ModalBuilder, PermissionFlagsBits, StringSelectMenuBuilder, TextInputBuilder, TextInputStyle, type ButtonInteraction, type ChatInputCommandInteraction, type Client, type Guild, type Interaction, type ModalSubmitInteraction } from "discord.js";
import type { BotContext } from "../types";
import type { FivemFinanceSettings, FivemFinanceTransaction } from "./apiClient";
import { renderComponentsV2Panel } from "./panelVisualRenderer";
import { systemComponentEmoji, systemEmojiText } from "./systemEmojiService";

const PREFIX="fivem_finance";
const pending=new Map<string,{guildId:string;input:Parameters<BotContext["api"]["createFivemFinanceTransaction"]>[1];expires:number}>();
const historySearches=new Map<string,string>();

export function startFivemFinanceService(client:Client<true>,context:BotContext){context.socket.onFivemFinancePanelPublish(p=>{const g=client.guilds.cache.get(p.guildId);if(g)void publishConfiguredFinancePanel(g,context)});const timer=setInterval(()=>{for(const[k,v]of pending)if(v.expires<Date.now())pending.delete(k)},60000);timer.unref();}
export async function publishFivemFinancePanel(interaction:ChatInputCommandInteraction,context:BotContext){if(!interaction.guild)return void await interaction.reply({content:"Use este comando em um servidor.",flags:MessageFlags.Ephemeral});const id=await publishConfiguredFinancePanel(interaction.guild,context,interaction.channelId);await interaction.reply({content:id?`Painel financeiro publicado em <#${id}>.`:"Configure e ative o financeiro antes de publicar.",flags:MessageFlags.Ephemeral});}
export async function showFivemFinanceBalance(interaction:ChatInputCommandInteraction,context:BotContext){if(!interaction.guild)return;const runtime=await context.api.getFivemFinanceRuntime(interaction.guild.id);await interaction.reply(v2Ephemeral("Saldo financeiro",summary(runtime.transactions)));}

export async function handleFivemFinanceInteraction(interaction:Interaction,context:BotContext){if(!("customId"in interaction)||!interaction.customId.startsWith(`${PREFIX}:`))return false;const[,action,arg]=interaction.customId.split(":");
  if(!interaction.guild)return true;const runtime=await context.api.getFivemFinanceRuntime(interaction.guild.id);const allowed=await canUse(interaction.guild,interaction.user.id,runtime.settings);if(!allowed){await denied(interaction,context);return true;}
  if(interaction.isButton()&&(action==="add"||action==="remove")){await showTransactionModal(interaction,action,runtime.settings);return true;}
  if(interaction.isModalSubmit()&&(action==="add_modal"||action==="remove_modal")){await submitModal(interaction,context,runtime.settings,action==="add_modal"?"add":"remove");return true;}
  if(interaction.isButton()&&action==="confirm"){await confirmPending(interaction,context,arg??"");return true;}
  if(interaction.isButton()&&action==="cancel_pending"){pending.delete(arg??"");await interaction.update(v2Ephemeral("Operação cancelada","Nenhuma movimentação foi registrada."));return true;}
  if(interaction.isButton()&&action==="history"){await showHistory(interaction,runtime.transactions,runtime.settings,0,"all","all");return true;}
  if(interaction.isButton()&&action==="history_search"){await interaction.showModal(new ModalBuilder().setCustomId(`${PREFIX}:history_search_modal`).setTitle("Pesquisar histórico").addComponents(new ActionRowBuilder<TextInputBuilder>().addComponents(new TextInputBuilder().setCustomId("query").setLabel("Gerente, ID, valor ou motivo").setRequired(false).setStyle(TextInputStyle.Short).setMaxLength(100))));return true;}
  if(interaction.isModalSubmit()&&action==="history_search_modal"){historySearches.set(`${interaction.guildId}:${interaction.user.id}`,interaction.fields.getTextInputValue("query").trim().toLowerCase());await showHistory(interaction,runtime.transactions,runtime.settings,0,"all","all");return true;}
  if(interaction.isStringSelectMenu()&&action==="history_filter"){const[type="all",period="all"]=(interaction.values[0]??"all_all").split("_");await showHistory(interaction,runtime.transactions,runtime.settings,0,type,period,true);return true;}
  if(interaction.isButton()&&action==="history_page"){const[page="0",type="all",period="all"]=(arg??"0-all-all").split("-");await showHistory(interaction,runtime.transactions,runtime.settings,Number(page),type,period,true);return true;}
  if(interaction.isButton()&&action==="managers"){await showManagers(interaction,runtime.transactions);return true;}
  if(interaction.isButton()&&action==="refresh"){await publishConfiguredFinancePanel(interaction.guild,context);await interaction.reply(v2Ephemeral("Painel atualizado","Os dados financeiros foram sincronizados."));return true;}return false;}

async function publishConfiguredFinancePanel(guild:Guild,context:BotContext,fallback?:string|null){const runtime=await context.api.getFivemFinanceRuntime(guild.id);const s=runtime.settings;if(!s.enabled)return null;const id=s.panelChannelId??fallback;if(!id)return null;const ch=await guild.channels.fetch(id).catch(()=>null);if(!ch?.isSendable())return null;const payload=mainPanel(s,runtime.transactions);let msg=s.panelMessageId&&"messages"in ch?await ch.messages.fetch(s.panelMessageId).catch(()=>null):null;if(msg)await msg.edit(payload);else{msg=await ch.send(payload);await context.api.updateFivemFinancePanelState(guild.id,msg.id)}return ch.id;}
function mainPanel(s:FivemFinanceSettings,tx:FivemFinanceTransaction[]){const active=tx.filter(x=>x.status!=="cancelled"),lastAdd=active.find(x=>x.type==="add"),lastRemove=active.find(x=>x.type==="remove"),last=active[0];return renderComponentsV2Panel({moduleId:"fivem-finance",accentColor:color(s.color),title:`${systemEmojiText("dinheiro")} Sistema Financeiro`,description:s.panelDescription,fields:[`## ${systemEmojiText("caixa")} Caixa Atual\n**Saldo total:** ${money(balance(active))}\n**Última atualização:** ${last?date(last.createdAt):"Nenhuma"}`,`**${systemEmojiText("liga")} Última adição:** ${lastAdd?`${lastAdd.managerName??lastAdd.username} • ${money(lastAdd.amount)}`:"Nenhuma"}\n**${systemEmojiText("porta")} Última retirada:** ${lastRemove?`${lastRemove.managerName??lastRemove.username} • ${money(lastRemove.amount)}`:"Nenhuma"}\n**${systemEmojiText("homem")} Último gerente:** ${last?.managerName??last?.username??"Nenhum"}\n**${systemEmojiText("prancheta_acertos")} Movimentações:** ${active.length}`],image:s.bannerMode==="none"?null:s.panelImage,actions:[new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`${PREFIX}:add`).setLabel("Adicionar Dinheiro").setEmoji(systemComponentEmoji("dinheiro")).setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`${PREFIX}:remove`).setLabel("Remover Dinheiro").setEmoji(systemComponentEmoji("porta")).setStyle(ButtonStyle.Danger)),new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`${PREFIX}:history`).setLabel("Ver Histórico").setEmoji(systemComponentEmoji("prancheta_acertos")).setStyle(ButtonStyle.Secondary).setDisabled(!s.historyEnabled),new ButtonBuilder().setCustomId(`${PREFIX}:managers`).setLabel("Ver Gerentes").setEmoji(systemComponentEmoji("homem")).setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId(`${PREFIX}:refresh`).setLabel("Atualizar Painel").setEmoji(systemComponentEmoji("relogio")).setStyle(ButtonStyle.Primary))]});}
async function showTransactionModal(i:ButtonInteraction,type:"add"|"remove",settings:FivemFinanceSettings){const modal=new ModalBuilder().setCustomId(`${PREFIX}:${type}_modal`).setTitle(type==="add"?"Adicionar dinheiro":"Remover dinheiro");for(const input of [["person","Nome da pessoa","Ex: João Silva"],["target","ID do usuário","ID do Discord"],["amount","Valor","Ex: 1500,00"],["reason","Motivo","Descreva a movimentação"]]as const)modal.addComponents(new ActionRowBuilder<TextInputBuilder>().addComponents(new TextInputBuilder().setCustomId(input[0]).setLabel(input[1]).setPlaceholder(input[2]).setRequired(input[0]!=="reason"||settings.requireReason).setStyle(input[0]==="reason"?TextInputStyle.Paragraph:TextInputStyle.Short).setMaxLength(input[0]==="reason"?1000:120)));await i.showModal(modal);}
async function submitModal(i:ModalSubmitInteraction,context:BotContext,s:FivemFinanceSettings,type:"add"|"remove"){const amount=parseMoney(i.fields.getTextInputValue("amount"));const target=i.fields.getTextInputValue("target").trim(),person=i.fields.getTextInputValue("person").trim(),reason=i.fields.getTextInputValue("reason").trim();if(!amount||amount<=0||amount>s.maxTransactionAmount)return void await i.reply(v2Ephemeral("Valor inválido",`O valor deve ser positivo e não pode ultrapassar ${money(s.maxTransactionAmount)}.`));if(!/^\d{5,32}$/.test(target))return void await i.reply(v2Ephemeral("ID inválido","Informe um ID válido do Discord."));const member=await i.guild!.members.fetch(i.user.id);const input={amount,proofImageUrl:"",type,userId:i.user.id,username:member.displayName,managerId:i.user.id,managerName:member.displayName,personName:person,targetUserId:target,reason,userAvatar:i.user.displayAvatarURL({size:256})};if(type==="remove"&&!s.allowNegativeBalance&&balance((await context.api.getFivemFinanceRuntime(i.guildId!)).transactions)-amount<0)return void await i.reply(v2Ephemeral("Saldo insuficiente","A retirada deixaria o caixa negativo."));if((type==="add"&&s.confirmAdd)||(type==="remove"&&s.confirmRemove)){const token=Math.random().toString(36).slice(2,10);pending.set(token,{guildId:i.guildId!,input,expires:Date.now()+300000});await i.reply({...v2Ephemeral("Confirmar movimentação",`${type==="add"?"Adicionar":"Remover"} **${money(amount)}** ${type==="add"?"ao":"do"} caixa?\n**Pessoa:** ${person}\n**Motivo:** ${reason}`),components:[{type:17,accent_color:type==="add"?0x22c55e:0xef4444,components:[{type:10,content:`## Confirmar movimentação\n${type==="add"?"Adicionar":"Remover"} **${money(amount)}**?`},new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`${PREFIX}:confirm:${token}`).setLabel("Confirmar").setStyle(type==="add"?ButtonStyle.Success:ButtonStyle.Danger),new ButtonBuilder().setCustomId(`${PREFIX}:cancel_pending:${token}`).setLabel("Cancelar").setStyle(ButtonStyle.Secondary))]}]});return;}await execute(i,context,input);}
async function confirmPending(i:ButtonInteraction,context:BotContext,token:string){const row=pending.get(token);if(!row||row.expires<Date.now())return void await i.reply(v2Ephemeral("Confirmação expirada","Abra o modal novamente."));pending.delete(token);await execute(i,context,row.input);}
async function execute(i:ButtonInteraction|ModalSubmitInteraction,context:BotContext,input:any){await i.deferReply({flags:MessageFlags.Ephemeral});const tx=await context.api.createFivemFinanceTransaction(i.guildId!,input);const runtime=await context.api.getFivemFinanceRuntime(i.guildId!);await sendLog(i.guild!,runtime.settings,tx);await publishConfiguredFinancePanel(i.guild!,context);await i.editReply(renderComponentsV2Panel({moduleId:"fivem-finance",accentColor:tx.type==="add"?0x22c55e:0xef4444,title:"Movimentação concluída",description:`**${tx.transactionId}**\n${money(tx.oldBalance)} → ${money(tx.newBalance)}\nPainel, histórico e estatísticas atualizados.`}));}
async function sendLog(g:Guild,s:FivemFinanceSettings,t:FivemFinanceTransaction){if(!s.logChannelId)return;const ch=await g.channels.fetch(s.logChannelId).catch(()=>null);if(!ch?.isSendable())return;await ch.send(renderComponentsV2Panel({moduleId:"fivem-finance",accentColor:t.type==="add"?0x22c55e:0xef4444,title:t.type==="add"?`${systemEmojiText("dinheiro")} Dinheiro Adicionado`:`${systemEmojiText("porta")} Dinheiro Removido`,description:`**Gerente:** <@${t.managerId??t.userId}> (${t.managerName??t.username})\n**Pessoa:** ${t.personName??"—"} • <@${t.targetUserId??t.userId}>\n**Valor:** ${money(t.amount)}\n**Motivo:** ${t.reason??t.notes??"—"}\n**Saldo antes:** ${money(t.oldBalance)}\n**Saldo depois:** ${money(t.newBalance)}\n**Data e hora:** ${date(t.createdAt)}`}));}
async function showHistory(i:any,all:FivemFinanceTransaction[],s:FivemFinanceSettings,page:number,type:string,period:string,update=false){const query=historySearches.get(`${i.guildId}:${i.user.id}`)??"";let rows=all.filter(x=>x.status!=="cancelled"&&(type==="all"||x.type===type));if(query)rows=rows.filter(x=>`${x.managerName??x.username} ${x.managerId??x.userId} ${x.targetUserId??""} ${x.amount} ${x.reason??x.notes??""}`.toLowerCase().includes(query));const days=period==="24h"?1:period==="7d"?7:period==="30d"?30:0;if(days)rows=rows.filter(x=>Date.now()-new Date(x.createdAt).getTime()<=days*86400000);const size=s.historyPageSize,pages=Math.max(1,Math.ceil(rows.length/size)),safe=Math.min(Math.max(page,0),pages-1),slice=rows.slice(safe*size,(safe+1)*size);const filter=new ActionRowBuilder<StringSelectMenuBuilder>().addComponents(new StringSelectMenuBuilder().setCustomId(`${PREFIX}:history_filter`).setPlaceholder("Filtrar histórico").addOptions([{label:"Todos",value:"all_all"},{label:"Apenas adições",value:"add_all"},{label:"Apenas retiradas",value:"remove_all"},{label:"Últimas 24 horas",value:"all_24h"},{label:"Últimos 7 dias",value:"all_7d"},{label:"Últimos 30 dias",value:"all_30d"}]));const nav=new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`${PREFIX}:history_page:${safe-1}-${type}-${period}`).setLabel("Anterior").setStyle(ButtonStyle.Secondary).setDisabled(safe===0),new ButtonBuilder().setCustomId(`${PREFIX}:history_search`).setLabel(query?`Busca: ${query.slice(0,20)}`:"Pesquisar").setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId(`${PREFIX}:history_page:${safe+1}-${type}-${period}`).setLabel("Próxima").setStyle(ButtonStyle.Secondary).setDisabled(safe>=pages-1));const payload=renderComponentsV2Panel({moduleId:"fivem-finance",accentColor:0x22c55e,title:`📜 Histórico • ${safe+1}/${pages}`,description:slice.length?slice.map(t=>`${t.type==="add"?"➕ Adição":"➖ Retirada"} • **${money(t.amount)}**\nGerente: ${t.managerName??t.username} (${t.managerId??t.userId})\nMotivo: ${t.reason??t.notes??"—"}\nSaldo: ${money(t.oldBalance)} → ${money(t.newBalance)}\n${date(t.createdAt)}`).join("\n\n"):"Nenhuma movimentação encontrada.",actions:[filter,nav]});const out={...payload,flags:Number(payload.flags)|MessageFlags.Ephemeral};update?await i.update(out):await i.reply(out);}
async function showManagers(i:any,all:FivemFinanceTransaction[]){const map=new Map<string,{name:string;add:number;remove:number;count:number;last:string}>();for(const t of all.filter(x=>x.status!=="cancelled")){const id=t.managerId??t.userId,v=map.get(id)??{name:t.managerName??t.username,add:0,remove:0,count:0,last:t.createdAt};v[t.type]+=t.amount;v.count++;if(t.createdAt>v.last)v.last=t.createdAt;map.set(id,v)}const rows=[...map].sort((a,b)=>(b[1].add+b[1].remove)-(a[1].add+a[1].remove));await i.reply(v2Ephemeral("👤 Gerentes",rows.length?rows.map(([id,v],n)=>`**${n+1}. ${v.name}** • ${id}\nAdicionado: ${money(v.add)} • Retirado: ${money(v.remove)}\nOperações: ${v.count} • Total: ${money(v.add+v.remove)}\nÚltima: ${date(v.last)}`).join("\n\n"):"Nenhuma movimentação registrada."));}
async function canUse(g:Guild,id:string,s:FivemFinanceSettings){const m=await g.members.fetch(id).catch(()=>null);return Boolean(m?.permissions.has(PermissionFlagsBits.Administrator)||m?.roles.cache.some(r=>s.useRoleIds.includes(r.id)||s.adminRoleIds.includes(r.id)));}
async function denied(i:any,context:BotContext){await context.api.postLog({guildId:i.guildId,userId:i.user.id,executorId:i.user.id,module:"fivem-finance",action:"access.denied",type:"security",message:"Tentativa sem permissão no sistema financeiro"}).catch(()=>null);await i.reply(v2Ephemeral("Acesso negado","Seu cargo não possui permissão para usar o Financeiro."));}
function summary(t:FivemFinanceTransaction[]){const active=t.filter(x=>x.status!=="cancelled");return `**Saldo:** ${money(balance(active))}\n**Entradas:** ${money(active.filter(x=>x.type==="add").reduce((n,x)=>n+x.amount,0))}\n**Saídas:** ${money(active.filter(x=>x.type==="remove").reduce((n,x)=>n+x.amount,0))}`;}
function v2Ephemeral(title:string,description:string){return {...renderComponentsV2Panel({moduleId:"fivem-finance",accentColor:0x22c55e,title,description}),flags:MessageFlags.IsComponentsV2|MessageFlags.Ephemeral};}
function balance(t:FivemFinanceTransaction[]){return t.reduce((n,x)=>n+(x.type==="add"?x.amount:-x.amount),0)}function money(n:number){return n.toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}function date(v:string){return new Date(v).toLocaleString("pt-BR")}function color(v:string){return Number.parseInt(v.replace("#",""),16)||0x22c55e}function parseMoney(v:string){return Number(v.replace(/\./g,"").replace(",",".").replace(/[^\d.]/g,""))}
