import { ActionRowBuilder, ButtonBuilder, ButtonStyle, ChannelType, Client, MessageFlags, ModalBuilder, PermissionFlagsBits, TextInputBuilder, TextInputStyle, type Interaction, type TextChannel } from "discord.js";
import type { BotContext } from "../types";
import type { Pd7Config, Pd7Request } from "./apiClient";
import { renderComponentsV2Panel } from "./panelVisualRenderer";
import { ensureFivemGoalChannelForUser } from "./fivemGoalService";
import { systemComponentEmoji, systemEmojiText, systemStatusEmoji } from "./systemEmojiService";
const PREFIX="pd7"; let started=false; const handled=new Map<string,string>();

export function startFivemPd7Service(client:Client,context:BotContext){if(started)return;started=true;const run=()=>void syncPanels(client,context);void run();const timer=setInterval(run,15000);timer.unref();}
export async function handleFivemPd7Interaction(interaction:Interaction,context:BotContext){
  if(!(interaction.isButton()||interaction.isModalSubmit())||!interaction.customId.startsWith(`${PREFIX}:`))return false;
  const [,action,id]=interaction.customId.split(":");
  if(action==="request"&&interaction.isButton()){const config=(await context.api.getPd7Configs()).find(c=>c.factionId===id&&c.guildId===interaction.guildId);if(!config)return fail(interaction,"Configuração PD7 indisponível.");const modal=new ModalBuilder().setCustomId(`${PREFIX}:submit:${config.factionId}`).setTitle(`PD7 • ${config.factionName}`);for(const f of config.fields.sort((a,b)=>a.order-b.order).slice(0,5))modal.addComponents(new ActionRowBuilder<TextInputBuilder>().addComponents(new TextInputBuilder().setCustomId(f.id).setLabel(f.label).setPlaceholder(f.placeholder??"Digite aqui").setRequired(f.required).setStyle(f.style==="paragraph"?TextInputStyle.Paragraph:TextInputStyle.Short).setMaxLength(f.style==="paragraph"?1000:200)));await interaction.showModal(modal);return true;}
  if(action==="submit"&&interaction.isModalSubmit()){const config=(await context.api.getPd7Configs()).find(c=>c.factionId===id&&c.guildId===interaction.guildId);if(!config||!interaction.guild)return fail(interaction,"Configuração PD7 indisponível.");await interaction.deferReply({flags:MessageFlags.Ephemeral});const fields=config.fields.sort((a,b)=>a.order-b.order).map(f=>({id:f.id,label:f.label,value:interaction.fields.getTextInputValue(f.id)}));const request=await context.api.createPd7Request({guildId:interaction.guild.id,factionId:config.factionId,userId:interaction.user.id,username:interaction.user.username,fields});const channel=await createChannel(config,request,interaction.guild,context);await interaction.editReply(`Solicitação criada em ${channel}.`);return true;}
  if(!id)return false; const request=await context.api.getPd7Request(id).catch(()=>null);if(!request||!interaction.guild)return fail(interaction,"Solicitação não encontrada.");const config=(await context.api.getPd7Configs()).find(c=>c.guildId===request.guildId&&c.factionId===request.factionId);if(!config)return fail(interaction,"Configuração removida.");if(!canManage(interaction,config))return fail(interaction,"Você não tem permissão para gerenciar este PD7.");
  if(action==="reject"&&interaction.isButton()){await interaction.showModal(new ModalBuilder().setCustomId(`${PREFIX}:reject_submit:${id}`).setTitle("Reprovar PD7").addComponents(new ActionRowBuilder<TextInputBuilder>().addComponents(new TextInputBuilder().setCustomId("reason").setLabel("Motivo da reprovação").setRequired(true).setStyle(TextInputStyle.Paragraph).setMaxLength(1000))));return true;}
  if(action==="approve"&&interaction.isButton()){await interaction.deferReply({flags:MessageFlags.Ephemeral});const member=await interaction.guild.members.fetch(request.userId);if(config.approvedRolePD7)await member.roles.add(config.approvedRolePD7,"PD7 aprovado");const goalChannelId=await ensureFivemGoalChannelForUser(context,interaction.guild,request.userId,member.displayName).catch(()=>null);await finish(request,config,"approved",interaction.user.id,null,context,interaction.channel as TextChannel);await context.api.postLog({guildId:interaction.guild.id,userId:request.userId,type:goalChannelId?"pd7.goal_activated":"pd7.goal_activation_skipped",message:goalChannelId?"PD7 aprovado e usuário vinculado ao sistema central de metas.":"PD7 aprovado; sistema de metas desativado ou indisponível.",metadata:{requestId:request._id,goalChannelId,source:"PD7"}}).catch(()=>null);await member.send(`Seu PD7 em **${config.factionName}** foi aprovado.${goalChannelId?` Canal de metas: <#${goalChannelId}>`:""}`).catch(()=>null);await interaction.editReply(goalChannelId?`PD7 aprovado e metas ativadas em <#${goalChannelId}>.`:"PD7 aprovado. O sistema de metas não estava disponível para ativacao.");return true;}
  if(action==="reject_submit"&&interaction.isModalSubmit()){await interaction.deferReply({flags:MessageFlags.Ephemeral});const reason=interaction.fields.getTextInputValue("reason");const member=await interaction.guild.members.fetch(request.userId);if(config.rejectedRolePD7)await member.roles.add(config.rejectedRolePD7,"PD7 reprovado");await finish(request,config,"rejected",interaction.user.id,reason,context,interaction.channel as TextChannel);await member.send(`Seu PD7 em **${config.factionName}** foi reprovado. Motivo: ${reason}`).catch(()=>null);await interaction.editReply("PD7 reprovado.");return true;}
  if(action==="close"&&interaction.isButton()){await interaction.deferReply({flags:MessageFlags.Ephemeral});await finish(request,config,"closed",interaction.user.id,null,context,interaction.channel as TextChannel);await interaction.editReply("Canal arquivado.");return true;} return false;
}
async function syncPanels(client:Client,context:BotContext){for(const c of await context.api.getPd7Configs().catch(()=>[])){if(!c.publishRequestedAt||handled.get(c._id)===c.publishRequestedAt)continue;handled.set(c._id,c.publishRequestedAt);const guild=client.guilds.cache.get(c.guildId);const channel=guild&&c.panelChannelPD7?await guild.channels.fetch(c.panelChannelPD7).catch(()=>null):null;if(!channel?.isTextBased())continue;const payload=renderComponentsV2Panel({accentColor:0x22c55e,guild,title:`${systemEmojiText("prancheta_acertos",guild)} PD7 • ${c.factionName}`,description:"Solicite seu PD7 pelo botão abaixo. Os dados serão enviados à equipe responsável.",actions:[new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`${PREFIX}:request:${c.factionId}`).setEmoji(systemComponentEmoji("acessar",guild)).setLabel("Solicitar PD7").setStyle(ButtonStyle.Primary))]});let message=null;if(c.panelMessageId)message=await channel.messages.fetch(c.panelMessageId).catch(()=>null);message?await message.edit(payload):message=await channel.send(payload);await context.api.updatePd7PanelState({guildId:c.guildId,factionId:c.factionId,panelMessageId:message.id});}}
async function createChannel(c:Pd7Config,r:Pd7Request,guild:any,context:BotContext){const overwrites=[{id:guild.roles.everyone.id,deny:[PermissionFlagsBits.ViewChannel]},{id:r.userId,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory]},{id:guild.members.me.id,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.ManageChannels,PermissionFlagsBits.SendMessages]} ,...c.allowedRolesPD7.map(id=>({id,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory]})),...c.responsibleUsersPD7.map(id=>({id,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory]}))];const name=`pd7-${r.username}`.toLowerCase().replace(/[^a-z0-9-]/g,"-").slice(0,90);const channel=await guild.channels.create({name,type:ChannelType.GuildText,parent:c.categoryPD7??undefined,permissionOverwrites:overwrites});const message=await channel.send(requestPanel(r,c,guild));await context.api.updatePd7Request(r._id,{channelId:channel.id,panelMessageId:message.id});await log(guild,c,`${systemEmojiText("acessar",guild)} PD7 criado por <@${r.userId}> • ${c.factionName}`);return channel;}
function requestPanel(r:Pd7Request,c:Pd7Config,guild:any){return renderComponentsV2Panel({accentColor:0xf59e0b,guild,title:`${systemEmojiText("prancheta",guild)} Solicitação PD7 • ${c.factionName}`,description:`**Solicitante:** <@${r.userId}>\n\n${r.fields.map(f=>`**${f.label}:**\n${f.value||"—"}`).join("\n\n")}`,actions:[new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(`${PREFIX}:approve:${r._id}`).setEmoji(systemComponentEmoji("visto",guild)).setLabel("Aprovar").setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId(`${PREFIX}:reject:${r._id}`).setEmoji(systemComponentEmoji("exclamacao",guild)).setLabel("Reprovar").setStyle(ButtonStyle.Danger),new ButtonBuilder().setCustomId(`${PREFIX}:close:${r._id}`).setEmoji(systemComponentEmoji("porta",guild)).setLabel("Fechar").setStyle(ButtonStyle.Secondary))]});}
async function finish(r:Pd7Request,c:Pd7Config,status:"approved"|"rejected"|"closed",actor:string,reason:string|null,context:BotContext,channel:TextChannel){await context.api.updatePd7Request(r._id,{status,handledBy:actor,rejectionReason:reason,resolvedAt:new Date().toISOString() as any});await channel.permissionOverwrites.edit(r.userId,{SendMessages:false});await channel.setName(`${status}-${channel.name}`.slice(0,100)).catch(()=>null);await log(channel.guild,c,`${status==="approved"?systemStatusEmoji("success",channel.guild):status==="rejected"?systemStatusEmoji("danger",channel.guild):systemEmojiText("porta",channel.guild)} PD7 ${status} • usuário <@${r.userId}> • responsável <@${actor}>${reason?`\nMotivo: ${reason}`:""}`);if(c.autoDeleteMinutes&&c.autoDeleteMinutes>0)setTimeout(()=>void channel.delete("Prazo de retenção PD7 concluído").catch(()=>null),c.autoDeleteMinutes*60000).unref();}
async function log(guild:any,c:Pd7Config,text:string){if(!c.logChannelPD7)return;const ch=await guild.channels.fetch(c.logChannelPD7).catch(()=>null);if(ch?.isTextBased())await ch.send(renderComponentsV2Panel({accentColor:0x5865f2,guild,title:`${systemEmojiText("folha",guild)} Log PD7`,description:`${text}\n<t:${Math.floor(Date.now()/1000)}:F>`})).catch(()=>null);}
function canManage(i:any,c:Pd7Config){return c.responsibleUsersPD7.includes(i.user.id)||i.memberPermissions?.has(PermissionFlagsBits.ManageGuild)||i.member?.roles?.cache?.some((r:any)=>c.allowedRolesPD7.includes(r.id));}
async function fail(i:any,message:string){if(i.replied||i.deferred)await i.followUp({content:message,flags:MessageFlags.Ephemeral});else await i.reply({content:message,flags:MessageFlags.Ephemeral});return true;}
